### ISSUE TITLE
Targets

### ISSUE THREAD

**Issue by DerHobbs** [bythewood/esrp_quests#3]
He doesn't spawn the targets reliably, I enter 13 targets, he spawns 12, other times I enter 10 and there are only 4 there, the problem is he still says I have to kill 10, which doesn't work because there are only 4 there are :D

**Comment by bythewood** [comment]
Make sure to place the targets 1 or 2 points higher Z than expected, otherwise they can spawn in the ground and fall into eternity. I'll add a check to make sure they spawn, though. :D

**Comment by bythewood** [comment]
@DerHobbs There we go, give the latest ([574754d](https://github.com/bythewood/esrp_quests/commit/574754dbbcf6eed51f94276a3401e90a10ac244c)) a try and let me know.

**Comment by DerHobbs** [comment]
It's working now, I'll add more missions tomorrow and let you know if I find anything else.

One more question, if I don't want to use XP and Gold, can I just omit it? Or do I have to write a 0

**Comment by bythewood** [comment]
You can omit it entirely. The code will default the values to 0 if not provided in the config.

**Comment by bythewood** [comment]
It handles the config with this:
```lua
  local questRewards = {}
  questRewards.Cash = 0
  if quest["Cash"] ~= nil then questRewards.Cash = quest["Cash"] end
  if quest["Reward"] ~= nil then questRewards.Cash = questRewards.Cash + quest["Reward"] end
  questRewards.Gold = 0
  if quest["Gold"] ~= nil then questRewards.Gold = quest["Gold"] end
  questRewards.Xp = 0
  if quest["Xp"] ~= nil then questRewards.Xp = quest["Xp"] end
  questRewards.Items = {}
  if quest["Items"] ~= nil then questRewards.Items = quest["Items"] end

  local questTargets = {}
  if quest["Targets"] ~= nil then questTargets = quest["Targets"] end
  if quest["Target"] ~= nil then questTargets[#questTargets+1] = quest["Target"] end
  if quest["Goal"] ~= nil then questTargets[#questTargets+1] = quest["Goal"] end
  ```
Where all values start as 0 and then if it sees a config for the value it uses it then.

**Comment by DerHobbs** [comment]
Wonderful, and really thanks for your work, I really think the changes are fantastic
