### ISSUE TITLE
Target position

### ISSUE THREAD

**Issue by DerHobbs** [bythewood/esrp_quests#4]
https://prnt.sc/iN_bVzAH__mh

So sometimes you have to make the Z 3-4 points higher, it's really difficult to organize everything, maybe there's a better solution, maybe similar to teleporting, that the npc automatically gets to the right height.

**Comment by DerHobbs** [comment]
especially in the mountains very very difficult, I then made Z higher and higher, then it was too high for some, not for others, it's almost impossible

**Comment by bythewood** [comment]
Thankfully that was just me being dumb and mishandling vector3 variables. Fixed in the push I just made. :D Let me know how it goes, it automatically moves the Z up 0.2 after each fail until it works.

**Comment by DerHobbs** [comment]
Seems to be running now :D can you already insert several items? or is that still not possible? if so, do you have an example config for it

**Comment by bythewood** [comment]
You certainly can do several items! Here's a mockup config entry for that:
```lua
	[5] = {
		["Type"] = 1,
		["Reward"] = 9,
		["Xp"] = 8,
		["Talk"] = {
			["Desc"] = "I need corn to feed my prize chickens! Will you help me?",
			["1"] = "Sure, no problem!",
			["2"] = "Why not feed them lesser chickens?",
			["3"] = "No. That's fowl."
		},
		["Reply"] = {
			["2"] = "Yes... YES! Brilliant! I will make the ALPHA CHICKEN!",
			["3"] = "Foul? No, it's just... Wait... Did you say foul or fowl?"
		},
		["Targets"] = {
			[1] = {
				["Name"] = "corn",
				["Pos"] = vector3(1053.6, -1128.1, 67.6),
				["Guards"] = {
					[1] = "A_C_Chicken_01",
				},
			},
			[2] = {
				["Name"] = "corn",
				["Pos"] = vector3(1050.7, -1118.3, 67.6),
				["Guards"] = {
					[1] = "A_C_Chicken_01",
				},
			},
		}
	},
```
