### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by RizzooTv** [bythewood/esrp_quests#5]
Hello,

What is really still missing is a timer that you can set, for example, so that the missions are automatically canceled after an hour, currently you need the command, but I think it would make sense to be able to say it definitely breaks after e.g. one hour and the npc will be deleted

**Comment by bythewood** [comment]
Honestly you're the first to request such a thing, although that's certainly worth adding. 😆 That should be easy enough to do, I'll add it to the soon™️ list!

**Comment by bythewood** [comment]
There we go, 1 hour timer implemented in the latest commit. 😄 Let me know if you have any suggestions, especially good ones like this.
