### ISSUE TITLE
Quests can be accepted multiple times

### ISSUE THREAD

**Issue by DerHobbs** [bythewood/esrp_quests#6]
I encounter the problem that my players are so stupid and 3 of them go to the NPC and accept the same mission 3 times, so 36 NPC spawn in the same place :D this is not good at all, maybe there is a possibility Keep blocking the mission until it's finished.

**Comment by bythewood** [comment]
There we go, in the latest commit each quest gets locked server-wide when accepted until that player completes it, runs out of time (1 hour), or logs off. 😄 That way only one player can run a quest at a time.
